// Generated by CoffeeScript 1.6.3
(function() {
  $(document).ready(function() {
    $("#hidden").on('click', function() {
      return window.console.log("by on");
    });
    $("#hidden2").click(function() {
      return window.console.log("by click");
    });
    return $(".ini").on('click', function() {
      return window.console.log('by on class');
    });
  });

}).call(this);
