// Generated by CoffeeScript 1.6.2
(function() {
  describe("document", function() {
    it("select body", function() {
      var res;

      res = $("body");
      return expect(typeof res).toEqual('object');
    });
    it("select head", function() {
      var res;

      res = $("head");
      return expect(typeof res).toEqual('object');
    });
    it("select html", function() {
      var res;

      res = $("html");
      return expect(typeof res).toEqual('object');
    });
    return it("select element by id", function() {
      var res;

      res = $("#target");
      return expect(typeof res).toEqual('object');
    });
  });

}).call(this);
